"""initial_migration

Revision ID: 8fa1ba5f33b5
Revises: 
Create Date: 2026-06-10 18:58:36.383349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fa1ba5f33b5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_anomalies_document_id'), table_name='anomalies')
    op.drop_index(op.f('idx_anomalies_invoice_id'), table_name='anomalies')
    op.drop_index(op.f('idx_anomalies_payroll_record_id'), table_name='anomalies')
    op.create_index(op.f('ix_anomalies_document_id'), 'anomalies', ['document_id'], unique=False)
    op.create_index(op.f('ix_anomalies_id'), 'anomalies', ['id'], unique=False)
    op.create_index(op.f('ix_anomalies_invoice_id'), 'anomalies', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_anomalies_payroll_record_id'), 'anomalies', ['payroll_record_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_id'), 'document_chunks', ['id'], unique=False)
    op.alter_column('documents', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_documents_created_at'), table_name='documents')
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_organization_id'), 'documents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_documents_workspace_id'), 'documents', ['workspace_id'], unique=False)
    op.alter_column('invoices', 'due_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('idx_invoices_document_id'), table_name='invoices')
    op.drop_index(op.f('idx_invoices_vendor_name'), table_name='invoices')
    op.create_index(op.f('ix_invoices_document_id'), 'invoices', ['document_id'], unique=False)
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_vendor_name'), 'invoices', ['vendor_name'], unique=False)
    op.alter_column('payroll_records', 'payment_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('idx_payroll_records_document_id'), table_name='payroll_records')
    op.drop_index(op.f('idx_payroll_records_employee_name'), table_name='payroll_records')
    op.create_index(op.f('ix_payroll_records_document_id'), 'payroll_records', ['document_id'], unique=False)
    op.create_index(op.f('ix_payroll_records_employee_name'), 'payroll_records', ['employee_name'], unique=False)
    op.create_index(op.f('ix_payroll_records_id'), 'payroll_records', ['id'], unique=False)
    op.drop_index(op.f('idx_processing_logs_document_id'), table_name='processing_logs')
    op.create_index(op.f('ix_processing_logs_document_id'), 'processing_logs', ['document_id'], unique=False)
    op.create_index(op.f('ix_processing_logs_id'), 'processing_logs', ['id'], unique=False)
    op.create_foreign_key(None, 'user_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_processing_logs_id'), table_name='processing_logs')
    op.drop_index(op.f('ix_processing_logs_document_id'), table_name='processing_logs')
    op.create_index(op.f('idx_processing_logs_document_id'), 'processing_logs', ['document_id'], unique=False)
    op.drop_index(op.f('ix_payroll_records_id'), table_name='payroll_records')
    op.drop_index(op.f('ix_payroll_records_employee_name'), table_name='payroll_records')
    op.drop_index(op.f('ix_payroll_records_document_id'), table_name='payroll_records')
    op.create_index(op.f('idx_payroll_records_employee_name'), 'payroll_records', ['employee_name'], unique=False)
    op.create_index(op.f('idx_payroll_records_document_id'), 'payroll_records', ['document_id'], unique=False)
    op.alter_column('payroll_records', 'payment_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_index(op.f('ix_invoices_vendor_name'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_document_id'), table_name='invoices')
    op.create_index(op.f('idx_invoices_vendor_name'), 'invoices', ['vendor_name'], unique=False)
    op.create_index(op.f('idx_invoices_document_id'), 'invoices', ['document_id'], unique=False)
    op.alter_column('invoices', 'due_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_index(op.f('ix_documents_workspace_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_organization_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.create_index(op.f('idx_documents_created_at'), 'documents', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('documents', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_document_chunks_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_anomalies_payroll_record_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_invoice_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_document_id'), table_name='anomalies')
    op.create_index(op.f('idx_anomalies_payroll_record_id'), 'anomalies', ['payroll_record_id'], unique=False)
    op.create_index(op.f('idx_anomalies_invoice_id'), 'anomalies', ['invoice_id'], unique=False)
    op.create_index(op.f('idx_anomalies_document_id'), 'anomalies', ['document_id'], unique=False)
    # ### end Alembic commands ###
